### ISSUE TITLE
[Feature]: automate JAR builds for releases and PRs

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#140]
### 👉 Please confirm the following

- [x] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 🤔 Is your proposal related to a problem?

[Once we have an executable JAR](https://github.com/jvondermarck/dinosaur-exploder/issues/139), we should automate its generation so that contributors and users can easily download and test the game without setting up the project locally.

### 😍 Describe the solution you'd like

- On GitHub releases: Automatically build and attach the JAR to the release.
- On Pull Requests: Build the JAR and upload it as an artifact for testing.

### 👍️ Describe alternatives you've considered

- Manually generating and uploading JARs, but this is tedious and prone to errors.

### ✍ Additional context

- This depends on the issue ["Generate an executable JAR for the game"](https://github.com/jvondermarck/dinosaur-exploder/issues/139) being completed first. Once that’s done, we can create a GitHub Action to handle the automation.

- ⚠ Note: If you're working on a fork, GitHub Actions won't run automatically on your PR. To test the CI before making a PR, you can:
  - Enable Actions on your fork by going to Settings > Actions and allowing workflows.
  - Push a test tag to trigger the release workflow (git tag test-release && git push origin test-release) or directly on the Github website rather than a command line.
  - Use act (a tool to run GitHub Actions locally): https://github.com/nektos/act.

**Comment by jvondermarck** [comment]
I think we could have something like this, it is just a Proof of Concept, but the goal is :

- `.github/workflows/release.yml`
```yaml

name: Build & Release JAR

on:
  release:
    types: [created]  # Trigger on release ?

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Can be wrong ?
          java-version: '21'
          cache: 'maven'

      - name: Build project with Maven
        run: mvn clean package

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3 # Check if it really exists ?
        with:
          name: DinosaurExploder-JAR
          path: target/*.jar # I think the .jar that is working is named "dinosaur-exploder-1.0.jar", there is another .jar generated under the name "original-dinosaur-exploder-1.0.jar" but I feel like it does not work, so choose the right one. You can test it on your own, by running the command `mvn clean package` 

      - name: Publish JAR to GitHub Releases
        uses: softprops/action-gh-release@v1  # Check if it really exists ?
        with:
          files: target/*.jar
````

- `.github/workflows/test-build.yml`
```yaml
name: Test JAR Build

on:
  pull_request:  # Trigger for each PR and also if we can, whenever someone update the PR with new commit, we should generate it again ? 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Can be wrong ?
          java-version: '21'
          cache: 'maven'

      - name: Build project with Maven
        run: mvn clean package

      - name: Upload JAR as artifact (for testing)
        uses: actions/upload-artifact@v3  # Check if it really exists ?
        with:
          name: DinosaurExploder-JAR-Test # Something like this ? maybe a dynamic name with the dinosaur-exploder-<ID of the PR>. ?
          path: target/*.jar
```
